### ISSUE TITLE
Plugin not properly saving on server shutdown

### ISSUE THREAD

**Issue by OldKingisdie** [AuraDevelopmentTeam/InvSync#32]
#### Issue Description:
Player's inventory don't sync when I restart my server.
Maybe the inventory not be Accurate save in mysql

#### Steps to reproduce:

I have a clock. 
add two sword . 
restart server. 
reentry server found two sword not be sync
...

____
#### Affected Versions (Do *not* use "latest"):

- Minecraft: 1.12.2
- InvSync: latest
- Sponge: 3472
- Other related mods: 
```
	| State     | ID                                | Version                     | Source                                             | Signature                                |
	|:--------- |:--------------------------------- |:--------------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft                         | 1.12.2                      | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | mcp                               | 9.42                        | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | FML                               | 8.0.99.99                   | forge-1.12.2-14.23.4.2705-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge                             | 14.23.4.2705                | forge-1.12.2-14.23.4.2705-universal.jar            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | jecharacters                      | 1.12.0-2.3.2                | JustEnoughCharacters-1.12.0-2.3.2.jar              | None                                     |
	| UCHIJAAAA | spongeapi                         | 7.1.0-ff990df               | [核心]spongeforge-1.12.2-2705-7.1.0-BETA-3472.jar    | None                                     |
	| UCHIJAAAA | sponge                            | 1.12.2-2705-7.1.0-BETA-3472 | [核心]spongeforge-1.12.2-2705-7.1.0-BETA-3472.jar    | 6729a677746f8cf63ef31881f913ed15d431b7f0 |
	| UCHIJAAAA | openmodscore                      | 0.11.5                      | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | foamfixcore                       | 7.7.4                       | minecraft.jar                                      | None                                     |
	| UCHIJAAAA | catclearlag                       | 0.8.3                       | [插件]CatClearLag-0.8.3.jar                          | None                                     |
	| UCHIJAAAA | placeholderapi                    | 4.4                         | [插件]PlaceholderAPI-4.4.jar                         | None                                     |
	| UCHIJAAAA | command-utils                     | 2.2.4                       | [插件]command-utils-2.2.4.jar                        | None                                     |
	| UCHIJAAAA | commandsync                       | 2.5                         | [插件]CommandSync.jar                                | None                                     |
	| UCHIJAAAA | pjc                               | 0.2.2                       | [插件]projectcore-7.1.0-0.2.2.jar                    | None                                     |
	| UCHIJAAAA | easykits                          | 0.2.0                       | [插件]easykits-7.1.0-0.2.0.jar                       | None                                     |
	| UCHIJAAAA | economylite                       | 2.15.0                      | [插件]EconomyLite-7.1.0-2.15.0.jar                   | None                                     |
	| UCHIJAAAA | nucleus                           | 1.6.0-S7.1                  | [插件]Nucleus-1.6.0-S7.1-MC1.12.2-plugin.jar         | None                                     |
	| UCHIJAAAA | nucleus-gluon                     | 1.0.4                       | [插件]Gluon-1.0.4.jar                                | None                                     |
	| UCHIJAAAA | holograms                         | 3.1.5                       | [插件]holograms-3.1.5.jar                            | None                                     |
	| UCHIJAAAA | hunger-keeper                     | 1.0.0                       | [插件]HungerKeeper-1.0.0.jar                         | None                                     |
	| UCHIJAAAA | invsync                           | 0.6.17                      | [插件]InvSync-0.6.17.jar                             | None                                     |
	| UCHIJAAAA | itemchat                          | 1.4.0                       | [插件]ItemChat-1.4.0.jar                             | None                                     |
	| UCHIJAAAA | joincommand                       | 1.1                         | [插件]JoinCommand-1.0-SNAPSHOT.jar                   | None                                     |
	| UCHIJAAAA | kt-skript                         | 1.1.3                       | [插件]kt-skript-1.1.3.jar                            | None                                     |
	| UCHIJAAAA | langswitch                        | 1.2                         | [插件]LangSwitch-1.2.jar                             | None                                     |
	| UCHIJAAAA | linkme                            | 1.4.0                       | [插件]LinkMe-1.4.0.jar                               | None                                     |
	| UCHIJAAAA | luckperms                         | 4.2.40                      | [插件]LuckPerms-Sponge-4.2.40.jar                    | None                                     |
	| UCHIJAAAA | mmcrestrict                       | 1.5.1                       | [插件]MMCRestrict-1.5.1-API-7.jar                    | None                                     |
	| UCHIJAAAA | multichat                         | 1.5                         | [插件]multichat-1.5.jar                              | None                                     |
	| UCHIJAAAA | noportal                          | 0.1.1                       | [插件]NoPortal-0.1.2.jar                             | None                                     |
	| UCHIJAAAA | npcs                              | 3.0.0                       | [插件]NPCs-3.0.0-1.12.2.jar                          | None                                     |
	| UCHIJAAAA | pixelautomessages                 | 1.0.3                       | [插件]PixelAutoMessages-1.0.3-b15.jar                | None                                     |
	| UCHIJAAAA | pjb                               | 0.2.0                       | [插件]projectborders-7.1.0-0.2.0.jar                 | None                                     |
	| UCHIJAAAA | inspector                         | 0.6.5                       | [插件]Re-Inspector-0.1.jar                           | None                                     |
	| UCHIJAAAA | serverteleport                    | 0.1.0-SNAPSHOT              | [插件]ServerTeleport-0.1.0-SNAPSHOT.jar              | None                                     |
	| UCHIJAAAA | stopspread                        | 0.1.1                       | [插件]StopSpread-0.1.1.jar                           | None                                     |
	| UCHIJAAAA | vshop                             | 1.9                         | [插件]VillagerShops-1.9.jar                          | None                                     |
	| UCHIJAAAA | virtualchest                      | 1.0.0-rc-1                  | [插件]VirtualChest-1.0.0-rc-1.jar                    | None                                     |
	| UCHIJAAAA | actuallyadditions                 | 1.12.2-r140                 | ActuallyAdditions-1.12.2-r140.jar                  | None                                     |
	| UCHIJAAAA | appliedenergistics2               | rv5-stable-11               | appliedenergistics2-rv5-stable-11.jar              | None                                     |
	| UCHIJAAAA | bdlib                             | 1.14.3.12                   | bdlib-1.14.3.12-mc1.12.2.jar                       | None                                     |
	| UCHIJAAAA | ae2stuff                          | 0.7.0.4                     | ae2stuff-0.7.0.4-mc1.12.2.jar                      | None                                     |
	| UCHIJAAAA | applecore                         | 3.1.3                       | AppleCore-mc1.12.2-3.1.3.jar                       | None                                     |
	| UCHIJAAAA | crafttweaker                      | 4.1.9                       | CraftTweaker2-1.12-4.1.9.jar                       | None                                     |
	| UCHIJAAAA | mtlib                             | 3.0.5                       | MTLib-3.0.5.jar                                    | None                                     |
	| UCHIJAAAA | modtweaker                        | 4.0.12                      | modtweaker-4.0.12.jar                              | None                                     |
	| UCHIJAAAA | jei                               | 4.11.0.204                  | jei_1.12.2-4.11.0.204.jar                          | None                                     |
	| UCHIJAAAA | appleskin                         | 1.0.9                       | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
	| UCHIJAAAA | betterbuilderswands               | 0.12.0                      | BetterBuildersWands-1.12-0.12.0.251.jar            | None                                     |
	| UCHIJAAAA | betterquesting                    | 3.5.266                     | BetterQuesting-3.5.266.jar                         | None                                     |
	| UCHIJAAAA | codechickenlib                    | 3.2.0.345                   | CodeChickenLib-1.12.2-3.2.0.345-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | redstoneflux                      | 2.0.2                       | RedstoneFlux-1.12-2.0.2.3-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | brandonscore                      | 2.4.3                       | BrandonsCore-1.12.2-2.4.3.168-universal.jar        | None                                     |
	| UCHIJAAAA | chameleon                         | 1.12-4.1.3                  | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| UCHIJAAAA | chisel                            | MC1.12.2-0.2.1.35           | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
	| UCHIJAAAA | cofhcore                          | 4.5.2                       | CoFHCore-1.12.2-4.5.2.19-universal.jar             | None                                     |
	| UCHIJAAAA | cofhworld                         | 1.2.0                       | CoFHWorld-1.12.2-1.2.0.5-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | mantle                            | 1.12-1.3.2.24               | Mantle-1.12-1.3.2.24.jar                           | None                                     |
	| UCHIJAAAA | endercore                         | 1.12.2-0.5.35               | EnderCore-1.12.2-0.5.35.jar                        | None                                     |
	| UCHIJAAAA | thermalfoundation                 | 2.5.0                       | ThermalFoundation-1.12.2-2.5.0.19-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | draconicevolution                 | 2.3.12                      | Draconic-Evolution-1.12.2-2.3.12.297-universal.jar | None                                     |
	| UCHIJAAAA | thermalexpansion                  | 5.5.0                       | ThermalExpansion-1.12.2-5.5.0.29-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | enderio                           | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderiointegrationtic             | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | twilightforest                    | 3.8.654                     | twilightforest-1.12.2-3.8.654-universal.jar        | None                                     |
	| UCHIJAAAA | tconstruct                        | 1.12.2-2.10.1.87            | TConstruct-1.12.2-2.10.1.87.jar                    | None                                     |
	| UCHIJAAAA | conarm                            | 1.0.1.2                     | conarm-1.12.2-1.0.1.2.jar                          | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJAAAA | containerfix                      | 1.0                         | ContainerFix+MC1.12.2+v1.0.jar                     | None                                     |
	| UCHIJAAAA | crafttweakerjei                   | 2.0.2                       | CraftTweaker2-1.12-4.1.9.jar                       | None                                     |
	| UCHIJAAAA | cucumber                          | 1.1.0                       | cucumber-1.12-1.1.0.jar                            | None                                     |
	| UCHIJAAAA | eiorteis                          | 1.12.2-3.0                  | eiorteis-3.0.jar                                   | None                                     |
	| UCHIJAAAA | enderiobase                       | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderioconduits                   | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderioconduitsappliedenergistics | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderioconduitsopencomputers      | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderioconduitsrefinedstorage     | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderiointegrationforestry        | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderiointegrationticlate         | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | ftblib                            | 5.2.0.30                    | FTBLib-5.2.0.30.jar                                | None                                     |
	| UCHIJAAAA | enderiomachines                   | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderiopowertools                 | 5.0.29                      | EnderIO-1.12.2-5.0.29.jar                          | None                                     |
	| UCHIJAAAA | enderstorage                      | 2.4.4.132                   | EnderStorage-1.12.2-2.4.4.132-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJAAAA | exnihilocreatio                   | 1.12-0.2.4                  | exnihilocreatio-1.12-0.2.4.jar                     | None                                     |
	| UCHIJAAAA | excompressum                      | 3.0.22                      | ExCompressum_1.12.2-3.0.22.jar                     | None                                     |
	| UCHIJAAAA | extracells                        | 2.5.13                      | ExtraCells-1.12.2-2.5.13a60.jar                    | None                                     |
	| UCHIJAAAA | extrautils2                       | 1.0                         | extrautils2-1.12-1.8.5.jar                         | None                                     |
	| UCHIJAAAA | zerocore                          | 1.12-0.1.2.2                | zerocore-1.12-0.1.2.2.jar                          | None                                     |
	| UCHIJAAAA | bigreactors                       | 1.12.2-0.4.5.49             | ExtremeReactors-1.12.2-0.4.5.49.jar                | None                                     |
	| UCHIJAAAA | fastleafdecay                     | v14                         | FastLeafDecay-v14.jar                              | None                                     |
	| UCHIJAAAA | foamfix                           | 0.9.9.1-1.12.2              | foamfix-0.9.9.1-1.12.2-anarchy.jar                 | None                                     |
	| UCHIJAAAA | ftbutilities                      | 5.2.0.32                    | FTBUtilities-5.2.0.32.jar                          | None                                     |
	| UCHIJAAAA | grimoireofgaia                    | 1.6.3                       | GrimoireOfGaia3-1.12.2-1.6.3.jar                   | None                                     |
	| UCHIJAAAA | infernalmobs                      | 1.7.5                       | InfernalMobs-1.12.2.jar                            | None                                     |
	| UCHIJAAAA | inventorytweaks                   | 1.63+release.109.220f184    | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | jaopca                            | 1.12.2-2.2.8.91             | JAOPCA-1.12.2-2.2.8.91.jar                         | None                                     |
	| UCHIJAAAA | oredictinit                       | 1.12.2-2.2.1.68             | JAOPCA-1.12.2-2.2.8.91.jar                         | None                                     |
	| UCHIJAAAA | longerdays                        | 1.0.4                       | longerdays-1.0.4.jar                               | None                                     |
	| UCHIJAAAA | lostcities                        | 2.0.11                      | lostcities-1.12-2.0.11.jar                         | None                                     |
	| UCHIJAAAA | mekanism                          | 1.12.2-9.4.13.349           | Mekanism-1.12.2-9.4.13.349.jar                     | None                                     |
	| UCHIJAAAA | mysticalagriculture               | 1.6.12                      | mysticalagriculture-1.12-1.6.12.jar                | None                                     |
	| UCHIJAAAA | mysticalagradditions              | 1.2.8                       | mysticalagradditions-1.12-1.2.8.jar                | None                                     |
	| UCHIJAAAA | nonetherportals                   | 1.0.0                       | nonetherPortals_v1.0.0formc1.12.2.jar              | None                                     |
	| UCHIJAAAA | openmods                          | 0.11.5                      | OpenModsLib-1.12.2-0.11.5.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAA | openblocks                        | 1.7.6                       | OpenBlocks-1.12.2-1.7.6.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| UCHIJAAAA | p455w0rdslib                      | 2.0.29                      | p455w0rdslib-1.12-2.0.29.jar                       | None                                     |
	| UCHIJAAAA | plustic                           | 6.5.2.0                     | plustic-6.5.2.0.jar                                | None                                     |
	| UCHIJAAAA | questbook                         | 3.1.1-1.12                  | questbook-3.1.1-1.12.jar                           | None                                     |
	| UCHIJAAAA | roughmobs                         | 2.0.0                       | roughmobs2-1.12.2_2.0.9.jar                        | None                                     |
	| UCHIJAAAA | bq_standard                       | 3.4.143                     | StandardExpansion-3.4.143.jar                      | None                                     |
	| UCHIJAAAA | storagedrawers                    | 1.12-5.3.5                  | StorageDrawers-1.12.2-5.3.7.jar                    | None                                     |
	| UCHIJAAAA | thermalcultivation                | 0.3.0                       | ThermalCultivation-1.12.2-0.3.0.7-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermaldynamics                   | 2.5.1                       | ThermalDynamics-1.12.2-2.5.1.14-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | thermalinnovation                 | 0.3.0                       | ThermalInnovation-1.12.2-0.3.0.7-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJAAAA | tinkersjei                        | 1.0                         | tinkersjei-1.0.jar                                 | None                                     |
	| UCHIJAAAA | tinkertoolleveling                | 1.12.2-1.0.5.DEV.30c7957    | TinkerToolLeveling-1.12.2-1.0.5.jar                | None                                     |
	| UCHIJAAAA | treegrowingsimulator              | 0.0.4                       | TreeGrowingSimulator2017-1.0.1.jar                 | None                                     |
	| UCHIJAAAA | wct                               | 3.9.67                      | WirelessCraftingTerminal-1.12.2-3.9.67.jar         | None                                     |
	| UCHIJAAAA | wrapup                            | 1.12-1.1.3                  | WrapUp-1.12-1.1.3.jar                              | None                                     |
```

**Comment by BrainStone** [comment]
First of all you used the version "latest", which the templated asked you not to use. Second it is not latest.  
So please update and see if it works now.

**Comment by OldKingisdie** [comment]
```
[01:17:45] [Server thread/ERROR] [invsync]: Could not save invetory for player chuxuan (ca1107cf-3d35-37e4-b2c4-2ba5db882e4d)
java.sql.SQLException: HikariDataSource HikariDataSource (HikariPool-1) has been closed.
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:81) ~[HikariDataSource.class:1.12.2-2705-7.1.0-BETA-3458]
	at world.jnc.invsync.util.database.DatabaseConnection.getConnection(DatabaseConnection.java:43) ~[DatabaseConnection.class:0.6.18.206]
	at world.jnc.invsync.util.database.DatabaseConnection.getPreparedStatement(DatabaseConnection.java:53) ~[DatabaseConnection.class:0.6.18.206]
	at world.jnc.invsync.util.database.DataSource.saveInventory(DataSource.java:114) [DataSource.class:0.6.18.206]
	at world.jnc.invsync.event.PlayerEvents.savePlayer(PlayerEvents.java:158) [PlayerEvents.class:0.6.18.206]
	at world.jnc.invsync.event.PlayerEvents.saveAllPlayers(PlayerEvents.java:133) [PlayerEvents.class:0.6.18.206]
	at world.jnc.invsync.event.PlayerEvents.close(PlayerEvents.java:141) [PlayerEvents.class:0.6.18.206]
	at world.jnc.invsync.InventorySync.removeEventListeners(InventorySync.java:223) [InventorySync.class:0.6.18.206]
	at world.jnc.invsync.InventorySync.stop(InventorySync.java:201) [InventorySync.class:0.6.18.206]
	at org.spongepowered.common.event.listener.GameStoppingEventListener_InventorySync_stop2.handle(Unknown Source) [?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) [RegisteredListener.class:1.12.2-2705-7.1.0-BETA-3458]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:383) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3458]
	at org.spongepowered.mod.event.SpongeModEventManager.extendedPost(SpongeModEventManager.java:443) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3458]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:404) [SpongeModEventManager.class:1.12.2-2705-7.1.0-BETA-3458]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:231) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3458]
	at org.spongepowered.common.SpongeImpl.postState(SpongeImpl.java:239) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3458]
	at org.spongepowered.common.SpongeImpl.postShutdownEvents(SpongeImpl.java:244) [SpongeImpl.class:1.12.2-2705-7.1.0-BETA-3458]
	at net.minecraft.server.dedicated.DedicatedServer.handler$postGameStoppingEvent$zoj000(DedicatedServer.java:830) [nz.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71240_o(DedicatedServer.java) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:589) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_162]
[01:17:45] [Server thread/INFO] [invsync]: Unloaded successfully!
```

**Comment by BrainStone** [comment]
Thank you. That is an error message I can work with. Should be fixed soon.

**Comment by BrainStone** [comment]
Try this version please: https://maven.project-creative.de/repository/auradev-snapshots/world/jnc/invsync/InvSync/0.6.19.208-DEV/InvSync-0.6.19.208-DEV.jar

Note that the server needs to run for a while before the issue could even occur.

**Comment by OldKingisdie** [comment]
How long should i run my server？It's always occur in InvSync-0.6.19.208-DEV

**Comment by BrainStone** [comment]
Try to do the same thing you did last time.

**Comment by OldKingisdie** [comment]
It‘s still occur when my server already ran over 10 minute 
The same issue

**Comment by BrainStone** [comment]
Ok. Can you enable debug in the config and recreate it again? And then I need your server log.
Upoad it to https://gist.github.com please.(As a secret gist) and link it here.

**Comment by BrainStone** [comment]
But first you can try this version: https://maven.project-creative.de/repository/auradev-snapshots/world/jnc/invsync/InvSync/0.6.19.208-DEV/InvSync-0.6.19.210-DEV.jar

Might fix it. Might also have worse performance.

**Comment by OldKingisdie** [comment]
so sad .....
https://maven.project-creative.de/repository/auradev-snapshots/world/jnc/invsync/InvSync/0.6.19.208-DEV/InvSync-0.6.19.210-DEV.jar
Error 404 Not Found

**Comment by BrainStone** [comment]
Oh. I'm stupid...

https://maven.project-creative.de/repository/auradev-snapshots/world/jnc/invsync/InvSync/0.6.19.210-DEV/InvSync-0.6.19.210-DEV.jar

That's the right link...

**Comment by OldKingisdie** [comment]
Amazing !! when I use debug mode it's fix
and I false the debug issue rise again

**Comment by OldKingisdie** [comment]
InvSync-0.6.19.210-DEV.jar 
This version is fix the bug~~~not need debug XD

**Comment by BrainStone** [comment]
Hi.

Could you help me out a little? I'm having a real hard time reproducing the issue. I wanted to try a different aproach.  
So if you don't mind, could you see if https://maven.project-creative.de/repository/auradev-snapshots/world/jnc/invsync/InvSync/0.6.19.242-data-source-DEV/InvSync-0.6.19.242-data-source-DEV.jar has the issue? That would be very interesting to know.

**Comment by OldKingisdie** [comment]
OK，I will use in my Server.But my server don't have Bauble mod
I will use this versoin :0.6.19.253-DEV

**Comment by BrainStone** [comment]
No. Please use the version I linked. It's testing some code that isn't in the current version on Ore.

**Comment by OldKingisdie** [comment]
OK，I will try to testing
And Ore‘s version can’t sync inventory with other version
For example，My old version use in 1 server，the new version use in 2 server. 1  and 2 not sync

**Comment by BrainStone** [comment]
Yeah. You should use the same version on both servers.

All I want you to do with the version linked here is see if you're having that issue with the diconnects at shutdown.

**Comment by OldKingisdie** [comment]
Sometimes  my server‘s player can't sync the inventory

**Comment by OldKingisdie** [comment]
Only find this , maybe it‘s not a stable version.
```
[18:47:45] [Server thread/WARN] [invsync]: Loading player student (277d11b1-5eb3-3766-b995-975fda450f17) failed because the previous server did not finish writing the data in time. Will synchronize anyway!
```

**Comment by BrainStone** [comment]
Perfect! Thank you
I'd recommend you use the latest beta now.
